kind: Pod
apiVersion: v1
metadata:
  name: kube-demo-gateway
  namespace: default
  labels:
    app: kube-demo-gateway
spec:
  volumes:
  containers:
  - name: kube-demo-gateway
    image: dockreg.datamation.gr/kube-demo-gateway:v1
    terminationMessagePolicy: File
    imagePullPolicy: Always
    securityContext:
      privileged: false
  restartPolicy: Always
  nodeName: minikube
  securityContext: {}
  imagePullSecrets:
  - name: localregistry
  schedulerName: default-scheduler

