kind: Service
apiVersion: v1
metadata:
  name: kube-demo-gateway
  namespace: default
  labels:
    app: kube-demo-gateway
spec:
  ports:
  - name: tcp-80-8080-c00d8
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31295
  selector:
    app: kube-demo-gateway
  type: NodePort
  sessionAffinity: None

